version: "3.8"
services:
  prd-drone-server:
    container_name: prd-drone-server
    image: drone/drone:latest
    restart: always
    env_file: prd-drone-server.env
    networks:
      - reverse-proxy
      - drone
    volumes:
      - ./data:/data

  prd-drone-runner:
    container_name: prd-drone-runner
    image: drone/drone-runner-docker:latest
    restart: always
    env_file: prd-drone-runner.env
    networks:
      - reverse-proxy
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  reverse-proxy:
    name: reverse-proxy
  drone:
    name: drone
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
